Refactor code to get different question forms
quizzard-edu/quizzard pull request #22
Opened 2017-10-03 18:50 UTC by mehtadarshan1

2017-10-06 00:14 UTC, esteeroramy requested changes
Couple of minor fixes here. Also will this PR include reformatting the question structure as discussed in the last meeting?

2017-10-06 00:14 UTC, esteeroramy commented on server.js
> +            //callback('type is not defined', null);
let's not keep coding comments in out codebase

2017-10-06 00:14 UTC, esteeroramy commented on server.js
> +            res.status(400).send("No question Type defined");
double quotes to single quotes please

2017-10-06 00:17 UTC, esteeroramy requested changes

2017-10-06 00:17 UTC, esteeroramy commented on server.js
> +        case 're':
changes here overlap with https://github.com/quizzard-edu/quizzard/pull/23/files

2017-10-06 00:22 UTC, ahmedqarmout2 requested changes

2017-10-06 00:22 UTC, ahmedqarmout2 commented on server.js
> +app.post('/questionFormAnswer', function(req, res){
hmmm i thought this is included in the other PR?!

2017-10-06 00:23 UTC, esteeroramy commented
If this PR is not valid anymore let's close it and just focus on the other one. Let us know why there is a duplication here please. Thanks :)

2017-10-07 20:08 UTC, Mohamed-A-Mohamed requested changes
Rejecting for now as this PR and PR #23 are working on similar things and I'm not sure which needs to be merged and which needs to be deleted.

2017-10-09 16:34 UTC, Mohammed-JS-Khan requested changes
As per the other comments, rejected due to conflicting changes with PR #23.

2017-10-09 16:51 UTC, closed without merging