Format consistency of question type values
quizzard-edu/quizzard pull request #23
Opened 2017-10-03 19:59 UTC by mehtadarshan1

2017-10-06 00:20 UTC, esteeroramy requested changes

2017-10-06 00:20 UTC, esteeroramy commented on public/js/admin.js
> +                getQuestionFormAnswer($(this).val());
it seems like there are 2 PRs open that change this specific line. what is happening here?

2017-10-06 00:20 UTC, esteeroramy commented on public/js/admin.js
> +                getQuestionFormAnswer($(this).val());
the same applies for all the other changes that conflict with https://github.com/quizzard-edu/quizzard/pull/22/files

2017-10-06 00:20 UTC, esteeroramy commented on server/questions.js
> +		case common.questionTypes.REGULAR:
I like this way more than in the other PR

2017-10-06 00:20 UTC, esteeroramy commented on views/question-creation.pug
> +      option(value='null' selected disabled) -- Select Question Type --
why do we have null in quotes here?

2017-10-06 00:20 UTC, esteeroramy commented on server.js
> +            res.status(400).send("No question Type defined");
double quotes to single quotes please

2017-10-06 00:20 UTC, esteeroramy commented on server.js
> +    switch (parseInt(req.body.qType)) {
what if it's not an int? can we guard against a possible error?

2017-10-06 00:22 UTC, ahmedqarmout2 requested changes

2017-10-06 00:22 UTC, ahmedqarmout2 commented on public/js/admin.js
> +        type: 'POST',
Is there a reason this is a post not get?

2017-10-06 00:22 UTC, ahmedqarmout2 commented on server.js
> +    switch (parseInt(req.body.qType)) {
I wonder if it would be better to move this to the questions file, what do you think?

2017-10-06 00:22 UTC, ahmedqarmout2 commented on views/question-creation.pug
> +      option(value='null' selected disabled) -- Select Question Type --
nice, well done.

2017-10-06 00:22 UTC, ahmedqarmout2 commented on views/question-creation.pug
> +      option(value='null' selected disabled) -- Select Question Type --
It would be better to have this refer to a similar enum like the one used by the backend rather than typing the actual values. So it would be something like, common.questionTypes.multi...

2017-10-06 00:25 UTC, esteeroramy commented
again, like I asked on the other PR. will this have changes regarding the file formatting as discussed in the last meeting?

2017-10-07 20:08 UTC, Mohamed-A-Mohamed requested changes
Rejecting for now as this PR and PR #22 are working on similar things and I'm not sure which needs to be merged and which needs to be deleted.

2017-10-09 16:36 UTC, Mohammed-JS-Khan requested changes
Should probably discuss this PR in person due to it being mixed with PR #22.

2017-10-09 16:51 UTC, closed without merging