Add materialize css
quizzard-edu/quizzard pull request #33
Opened 2017-10-08 03:51 UTC by ahmedqarmout2

This will include the library files needed for the new style to work. I also applied a sample of the new design on the login page.
![canva-photo-editor](https://user-images.githubusercontent.com/22353983/31313757-6e8147e2-abba-11e7-9be9-33e1f5c64212.png)

2017-10-09 16:40 UTC, Mohammed-JS-Khan commented on views/login.pug
> +  link(rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons")
Single quotes here for 'stylesheet' please.

2017-10-09 16:41 UTC, Mohammed-JS-Khan commented on views/login.pug
> +  link(rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons")
And for the href, all on line 6 though.

2017-10-09 16:42 UTC, Mohammed-JS-Khan requested changes
Look pretty nice. Good find Ahmed. Just minor changes.

2017-10-09 16:49 UTC, Mohammed-JS-Khan commented
See also #35, has conflicts.

2017-10-09 16:55 UTC, mehtadarshan1 approved these changes
Looks good to me

2017-10-10 00:15 UTC, Mohamed-A-Mohamed approved these changes
New style looks great

2017-10-10 00:27 UTC, Mohammed-JS-Khan approved these changes

2017-10-10 00:32 UTC, merged